
theme: jekyll-theme-tactile
title: Twitter - public treatment of American politicians
description: New description
menu: [
{'name': 'Overview', 'pagename': 'index'},
{'name': 'Data and Methodology', 'pagename': 'page1'},
{'name': 'Demographics', 'pagename': 'page2'},
{'name': 'Network Analysis', 'pagename': 'page3'},
{'name': 'Contingency Matrix', 'pagename': 'page4'},
{'name': 'Topic Modeling', 'pagename': 'page5'},
{'name': 'Conclusion', 'pagename': 'page6'},
]
