theme: jekyll-theme-tactile
title: Public Treatment of American politicians on Twitter
description: 
menu: [ 
{'name': 'Overview', 'pagename': 'index'},
{'name': 'Data and Methodology', 'pagename': 'page1'},
{'name': 'By Gender', 'pagename': 'page2'},
{'name': 'By Age', 'pagename': 'page3'},
{'name': 'By Sexual Orientation', 'pagename': 'page4'},
{'name': 'By Ethnicity', 'pagename': 'page5'},
{'name': 'Topic Modeling', 'pagename': 'page6'},
{'name': 'Demographics', 'pagename': 'page7'},
{'name': 'Limitations. How to solve them?', 'pagename': 'page8'},
]
